Update shift

diff --git a/shift b/shift
--- a/shift
+++ b/shift
@@ -72,7 +72,7 @@ MAX_TRIES=5
 function nodeIsReady() {
   # todo: need a new docker version to use --since
   # use --since 1 minute to try to filter out old log messages
-  docker-compose logs node | grep "SHIFT to Bikes listening"
+  sub_compose logs node | grep "SHIFT to Bikes listening"
 }
 
 function waitUntilServiceIsReady() {
@@ -88,7 +88,7 @@ function waitUntilServiceIsReady() {
   done
 
   if [ $attempt -gt $MAX_TRIES ]; then
-    echo "Error: $2 not responding, cancelling set up"
+    echo "Error: $2 never found successful log message. You may need to debug."
     exit 1
   fi
 }
@@ -168,17 +168,12 @@ sub_attach() { # <service>        - Run bash on a running service
 }
 
 sub_compose() { # <cmd...>        - Run a compose with associated files
-    OS=`uname`
-    OSAlt=`uname -o`
-    if [ "$OS" == "Darwin" ] ; then
-	    docker compose $@
-    elif [ "$OS" == "Linux" ] ; then
-	    docker-compose $@
-    elif [ "$OSAlt" == "Msys" ] ; then
-      docker-compose $@
-    else
-	    echo "if docker compose isn't working, please email bikecal@shift2bikes.org to let us know"
-	    exit 255
+    if hash docker-compose 2>/dev/null; then
+        docker-compose $@
+    elif hash docker 2>/dev/null; then
+        docker compose $@
+    else 
+       echo >&2 "Can't find docker. Aborting."; exit 1;
     fi
 }
 
@@ -207,7 +202,7 @@ sub_mysqldump() { #               - Dump the mysql database
 
 sub_backup() { #                  - Backup the mysql database
     cd "${ROOT}"
-    docker-compose exec -T db mysqldump -u ${MYSQL_USER} -h db -P 3306 -p"${MYSQL_PASSWORD}" --no-tablespaces ${MYSQL_DATABASE} | gzip -c > /tmp/mysql-$(date +%F).out.gz
+    sub_compose exec -T db mysqldump -u ${MYSQL_USER} -h db -P 3306 -p"${MYSQL_PASSWORD}" --no-tablespaces ${MYSQL_DATABASE} | gzip -c > /tmp/mysql-$(date +%F).out.gz
     aws s3 cp /tmp/mysql-$(date +%F).out.gz s3://shift2bikes-backups-us-west-2/
 }
 
