wait for node before finishing "shift up"
works by polling the docker log file.
uses "--since" to avoid seeing old log entries; and adds an increasing sleep each time.

diff --git a/shift b/shift
--- a/shift
+++ b/shift
@@ -66,6 +66,39 @@ fi
 
 SCRIPT_NAME=$(basename $0)
 
+# ====================
+# https://www.marksayson.com/blog/wait-until-docker-containers-initialized/
+
+# Max query attempts before consider setup failed
+MAX_TRIES=5
+
+# Return true-like values if and only if logs
+# contain the expected "ready" line
+function nodeIsReady() {
+  # use --since 1 minute to try to filter out old log messages
+  docker-compose logs node --since 1m | grep "SHIFT to Bikes listening"
+}
+
+function waitUntilServiceIsReady() {
+  attempt=1
+  while [ $attempt -le $MAX_TRIES ]; do
+    if "$@"; then
+      echo "$2 container is up!"
+      break
+    fi
+    echo "Waiting for $2 container... (attempt: $((attempt++)))"
+    # wait more each time; hopefully less than --since
+    sleep $((3*attempt))
+  done
+
+  if [ $attempt -gt $MAX_TRIES ]; then
+    echo "Error: $2 not responding, cancelling set up"
+    exit 1
+  fi
+}
+
+# ====================
+
 sub_help() { #                    - Show this text
     echo "Usage: ./${SCRIPT_NAME} <subcommand> [options]"
     echo "Subcommands:"
@@ -109,6 +142,8 @@ sub_reload() { # <service>, ...   - Trigger a code/conf reload
 
 sub_start() { # <service>, ..     - Start service(s)
     sub_compose up --force-recreate -d $@
+    # tbd: for staging, could also check for "mysqld: ready for connections."
+    waitUntilServiceIsReady nodeIsReady "node"
 }
 
 sub_stop() { # <service>, ...     - Stop service(s)
