autocreate SSL directory if it is missing

diff --git a/shift b/shift
--- a/shift
+++ b/shift
@@ -63,8 +63,12 @@ sub_help() { #                    - Show this text
 }
 
 sub_up() { #                      - Bring all services up
+    if [ ! -d $LETSENCRYPT_WEBROOT ] ; then
+	mkdir $LETSENCRYPT_WEBROOT
+    fi 
     sub_compose up --force-recreate -d ${CONTAINERS}
-    echo "Run './${SCRIPT_NAME} watch' to monitor for changes and rebuild"
+    echo "Assuming no fatal errors are shown above, you can now use the environment!"
+    echo "You can run './${SCRIPT_NAME} watch' to monitor for changes and rebuild."
 }
 
 sub_watch() { #                   - Watch the site directory for changes and rebuild the site
@@ -118,6 +122,7 @@ sub_attach() { # <service>        - Run bash on a running service
 
 sub_compose() { # <cmd...>        - Run a compose with associated files
     docker-compose $@
+    return $?
 }
 
 sub_logs() { # <service>, ...     - Show last 50 lines and attach to a service
